### ISSUE TITLE
The debug version does not load the models

### ISSUE THREAD

**Issue by spiovesan** [intel-iot-devkit/machine-operator-monitor-cpp#2]
Running debug version the `readNet` call causes a `Exception thrown at 0x00007FFF6EAC0301 (inference_engine.dll) in machine-operator-monitor.exe: 0xC0000005: Access violation reading location 0x0000000000000019.`.
With the same parameters it work in release version.
Im using Windows10 with VS2019, openvino_2019.3.379 with its opencv_dnn412.dll

**Comment by MandipJ** [comment]
This application has been tested only on Ubuntu OS as mentioned in the Readme.

**Comment by zahidulhaque** [comment]
Closing the issue as the application has been developed and validated on Ubuntu.
